### ISSUE TITLE
Problem with Print the Chart

### ISSUE THREAD

**Issue by lena31** [VFPX/FoxCharts#8]
Hallo,
I have Problem with the function To Print(), because it doesn't print the chart and I need a function with print the Diagram.

Regards
Lena

**Comment by ggreen86** [comment]
I use the method SaveToFile() to save an image of the chart as a PNG file.  Then I have a report with an image as the only object that I then print.


________________________________

**Comment by lena31** [comment]
Thank for your help

Regards
Lena
